sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - build-essential
notifications:
  slack:
    if: branch = dev
      slack: purduehcr:m186O0Sy1WQNMWeSOoj36urC

before_install:
- npm update
- export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$LOCAL
- make
- make install
- cd -
- export PATH="$LOCAL/bin:$PATH"
- cd functions
- curl -sL https://firebase.tools | bash
- firebase setup:emulators:firestore
install:
- npm install
script:
- npm test
